### ISSUE TITLE
request for 4.1.11.1 release

### ISSUE THREAD

**Issue by apsoto** [rosenfeld/active_record_migrations#10]
Hi There,

Rails 4.1.11 just was released.  Just wondering how long before you have a chance to release new versions. 

Thanks.

**Comment by rosenfeld** [comment]
I've just released the latest one 4.2.2. I don't maintain support for older versions myself. Feel free to send a pull request for 4.1.11 if you're interested on it. Or you may want to use the optimistic branch that should work with any Rails version >= 4.0.0 released so far:

https://github.com/rosenfeld/active_record_migrations/tree/optimistic

I can't guarantee it will keep working for future releases because I rely on some internal implementation details of the migration generator and it could change anytime. This method implementation hasn't changed since 4.0.0 at least so it should work for all released versions so far.

**Comment by apsoto** [comment]
optimistic looks like it works thanks.  Maybe add to the README usage:

    gem 'active_record_migrations', git: 'https://github.com/rosenfeld/active_record_migrations.git', branch: 'optimistic'

**Comment by rosenfeld** [comment]
I already did it a while ago. See the last topic before Contributing.

**Comment by rosenfeld** [comment]
Also, you don't have to source the repository and branch. I actually released a gem for that branch. Please check out the README of the `optimistic` branch.

**Comment by apsoto** [comment]
Thanks.  Didn't see that.
