### ISSUE TITLE
Support for DATABASE_URL

### ISSUE THREAD

**Issue by andrhamm** [rosenfeld/active_record_migrations#18]
I find using the DATABASE_URL environment variable handy in some cases. It would be great if this library could add support for it instead of YAML config in the Rails style of `config/database.yml`.

**Comment by rosenfeld** [comment]
This library is supposed to be a thin wrapper around ActiveRecord migrations without any changes to the default settings provided by AR. I don't use the YAML configuration myself in my application (have never used actually) but I keep the AR defaults anyway in this gem. I don't use environment variables either in my deploys. I store all settings in a single Ruby configuration file which is generated by our deploy tool during the deploy process, but if you want to use environment variables it should be straightforward by reading the examples in the README. Just use `ENV['DATABASE_URL']` rather than a fixed set of options. Here's the example in the README:

```ruby
ActiveRecordMigrations.configure do |c|
  c.database_configuration = {
    'development' => {'adapter' => 'sqlite3', 'database' => 'db/custom.sqlite3'},
  }
  # Other settings:
  c.schema_format = :sql # default is :ruby
  # c.yaml_config = 'db/config.yml'
  # c.environment = ENV['db']
  # c.db_dir = 'db'
  # c.migrations_paths = ['db/migrate'] # the first entry will be used by the generator
end
```
