### ISSUE TITLE
activerecord 4.2.7 is missing a release

### ISSUE THREAD

**Issue by teadur** [rosenfeld/active_record_migrations#19]
It seems its impossible to upgrade to activerecord 4.2.7 with active_record_migrations.

**Comment by rosenfeld** [comment]
I usually run the migrations as a separate stand-alone project, so if I used ActiveRecord for anything else in my other projects, their versions could be different. If you use active_record along with active_record_migrations in the same project, then yes, unless I release the same version as your project uses, Bundler won't allow both. In that case, I suggest you to use the optimistic gem:

https://github.com/rosenfeld/active_record_migrations/tree/optimistic

```ruby
gem 'active_record_migrations', '5.0.0.1.pre.optimistic'
# or gem 'active_record_migrations', '4.0.0.0.pre.optimistic'
```

The internal implementation of the generator hasn't changed in ActiveRecord since AR migrations was created but it might change at some point and that's why the optimistic is not the default. If you can't upgrade yet to a newer version of ActiveRecord, please use the optimistic version in the meanwhile.

**Comment by rosenfeld** [comment]
The specific bit I'm concerning about is this:

https://github.com/rosenfeld/active_record_migrations/blob/master/lib/active_record_migrations/generators/migration.rb

If they change their current implementation of `create_migrate_file` things might break. I've already submitted some PR's to fix this upstream some years ago but they were ignored, so until they fix this, if we want to support user specified migration path, we must change the implementation of `create_migrate_file` or migrations would be always generated under db/migrate:

https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration/migration_generator.rb#L14

So, if we rely only on the public API behavior, we wouldn't be able to specify the migrations path.
