### ISSUE TITLE
NoMethodError: undefined method `root' for Rails:Module

### ISSUE THREAD

**Issue by ravinggenius** [rosenfeld/active_record_migrations#20]
I'm building a gem for internal company use. The gem needs to create migrations, but doesn't need to run them, except maybe for tests. I have a number of projects which depend on the gem. I tried to create a sample migration to see what gets generated, but I got an error (stack trace below).

I thought this gem replicated ActiveRecord Rake tasks so one could use ActiveRecord without Rails. After getting the error, I search through ActiveRecordMigrations' source code and found two references to `Rails.root`:

See https://github.com/rosenfeld/active_record_migrations/blob/d6c52d0a9ee21d694bf49239be8ba3ae6b589c59/lib/active_record_migrations.rb#L34
See https://github.com/rosenfeld/active_record_migrations/blob/e761c10ec3a09663ac50d565a8f0a87afe0ac980/lib/active_record_migrations/tasks/new_migration.rake#L30-L31

The only thing I need ActiveRecordMigrations for in my internal gem is to create migrations. Should I just roll my own generator, or is Rails mistakenly being used here?

```
$ bundle exec rake db:new_migration\[add_foo_to_bars\] --trace
** Invoke db:new_migration (first_time)
** Execute db:new_migration
rake aborted!
NoMethodError: undefined method `root' for Rails:Module
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active_record_migrations-5.0.0.2/lib/active_record_migrations/tasks/new_migration.rake:31:in `block (2 levels) in <top (required)>'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.3.1/bin/rake:23:in `load'
/usr/local/opt/rbenv/versions/2.3.1/bin/rake:23:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.3.1/bin/bundle:23:in `load'
/usr/local/opt/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:new_migration
```

**Comment by rosenfeld** [comment]
I can't replicate it here. Also, you don't need to escape the brackets. What's the content of your Rakefile?

I don't have the time to replicate AR features, so I simply wrap them. Unfortunately the way ActiveRecord and Rails are written will require the `railties` gem for running the generator, which is the gem that defines Rails. When ActiveRecord generator gets decoupled from the `railties` gem I should be able to remove that dependency on active_record_migrations. You can see more details here:

https://github.com/rosenfeld/active_record_migrations/issues/8

**Comment by ravinggenius** [comment]
By the way I'm on zsh, so brackets have to be escaped. I just made a quick Rack task to do the basic file generator myself, so no worries. I just thought it was weird to be referencing `Rails.root` in a project that is ostensibly **not** a Rails app.

My `Rakefile` looked like this when I got the error, *I think*:

```ruby
begin
  require 'bundler/gem_tasks'
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'active_record_migrations'

ActiveRecordMigrations.load_tasks
```

**Comment by rosenfeld** [comment]
I find your behavior very weird. This doesn't cause any errors like that here: `bundle exec ruby -e 'require "rails"; puts Rails.root'`. These are the lines I care about from your stacktrace:

```
NoMethodError: undefined method `root' for Rails:Module
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active_record_migrations-5.0.0.2/lib/active_record_migrations/tasks/new_migration.rake:31:in `block (2 levels) in <top (required)>'
```

Rails is required here: https://github.com/rosenfeld/active_record_migrations/blob/d6c52d0a9ee21d694bf49239be8ba3ae6b589c59/lib/active_record_migrations.rb#L4

So, why isn't Rails.root method defined if the command-line above works? Since I can't replicate the issue I can't explain, which means I can't fix it. Stop using Rails.root wouldn't fix anything because the generator relies on Rails anyway, that's why I create a fake Rails application.

Have you looked at the `standalone_migrations` gem?

https://github.com/thuss/standalone-migrations

They do also seem to use a minimal Rails app, but maybe that works for you. There are many other migrations frameworks out there if you don't want to create your own (I haven't tried them yet):

https://github.com/ivpusic/migrate
https://github.com/theory/sqitch
https://github.com/aphel-bilisim-hizmetleri/pg-migrator

**Comment by ravinggenius** [comment]
Thanks for the links; I found yours first so that's what I went with (I was following https://gist.github.com/ajw725/103d0ceacb1048cd9faa). I may have been holding something wrong, but I managed to hack together what I need, so no worries.

**Comment by rosenfeld** [comment]
It's interesting how the use cases differ. I created this project because I'm interested on the ActiveRecord migrations but have no interest in using ActiveRecord as an ORM. I like its migrations framework but I much prefer Sequel over ActiveRecord as an ORM. Also, I prefer to handle the migrations as a completely separated project, so I never experience conflicts of any kind. However it seems there are some people that want to use ActiveRecord both as an ORM and to manage the migrations, but are not interested in Rails, but want to keep the migrations in the same project rather than as a separate project... Maybe it might make more sense in those cases to use different Gemfiles, one for the project and another one for the migrator tool.

**Comment by ravinggenius** [comment]
My project began as an abstraction of helpers from multiple similar Rails apps. I moved the common bits into a Rails engine. Now I'm trying to remove the Rails engine portion of the project and just leave a library. However this library needs to provide migrations for the (used to be Rails, but now CLI) apps which use it. These CLI apps (will) use active_record_migrations to manage running the migrations copied from the library.

In short it's complicated.

**Comment by rosenfeld** [comment]
Maybe it might be simpler if you created a simple server that would listen to requests to migrate the database to some specific version and your CLI apps could migrate by making requests to this server. This is also safer in my opinion since the server would be able to ensure a single migration process would be running at a given time and avoid issues that could be caused by multiple migration processes running concurrently...

**Comment by ravinggenius** [comment]
Each app gets its own database, so why should I be concerned about concurrent migrations? In practice we don't have many migrations anyway.

**Comment by rosenfeld** [comment]
Ah, I thought they would share the same database...
