### ISSUE TITLE
Render-related gems should not be dependencies

### ISSUE THREAD

**Issue by Ravenstine** [rosenfeld/active_record_migrations#8]
I'm not sure why this gem is requiring the following gems:

- rails-deprecated-sanitizer
- rails-dom-testing
- rails-html-sanitizer
- actionview

I can't imagine why a migrations gem would need these.  Even the necessity for railties is questionable, since ActiveRecord should be the only "railtie".

I wanted to use this gem because I wanted ActiveRecord migrations without the overhead that Rails adds, but upon discovering this extra Rails baggage I won't use it.  I suspect that there are others who would use this gem for the same reasons.  It looks like a nice gem, otherwise.  Consider removing the dependencies I listed.

**Comment by rosenfeld** [comment]
The problem is that ActiveRecord migrations themselves rely on the `railties` gem, so we have too:

https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration.rb#L1
https://github.com/rails/rails/blob/master/railties/lib/rails/generators/migration.rb

Once you are able to convince the Rails team to change their approach and move this code out of `railties` to some smaller gem I'll be able to remove the explicit dependency on `railties` (currently the dependency already exists for the Rails migrations but since you're able to use AR without the migrations it's possible to do so without requring `railties`, that's probably the reason why the dependency is not explicit on their side).

Since I won't consider copying a significant amount of code from AR and Railties to this project just to get rid of the dependency there's nothing I can do to fix this until you're able to convince the Rails core team to remove this dependency.
